apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "dp-rapp-api"
  namespace: "raptus"
  labels:
    "team": "raptus"
spec:
  image: {{image}}
  liveness:
    path: "/internal/isready"
    port: 8080
    initialDelay: 60
    timeout: 10
    periodSeconds: 300
  readiness:
    path: "/internal/isready"
    port: 8080
    initialDelay: 60
    timeout: 10
    periodSeconds: 30
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: /actuator/prometheus
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  ingresses: 
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: "dp-rapp-api-db"
            envVarPrefix: DB
  kafka:
    pool: {{ kafkaPool }}
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: dp-rapp-frontend-q1
        - application: dp-rapp-frontend-q2
        - application: dp-rapp-frontend
