spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 5
  flyway:
    enabled: true
    locations: classpath:/db/migration
  kafka:
    consumer:
      group-id: ${KAFKA_GROUP_ID:dp-rapp-api}
    bootstrap-servers: ${KAFKA_BROKERS}
    properties:
      security:
        protocol: SSL
      ssl:
        keystore:
          type: PKCS12
          location: ${KAFKA_KEYSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
        truststore:
          type: PKCS12
          location: ${KAFKA_TRUSTSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: prometheus, metrics
app:
  kafka:
    topic:
      meldepliktperiode: raptus.meldepliktperiode-v1
